spring:
  application:
    name: spring-cloud-euerka-client
server:
  port: 9998
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true